--[[
	Bagnon Config Localization Information: English Language
		This file must be present to have partial translations
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'enUS', true)

L.Columns = 'Columns'
L.Scale = 'Scale'
L.Spacing = 'Spacing'
L.Opacity = 'Opacity'
L.FrameColor = 'Frame Color'
L.FrameBorderColor = 'Frame Border Color'
L.Frame = 'Frame'
L.Inventory = 'Inventory'
L.Bank = 'Bank'
L.KeyRing = 'Keyring'
L.GuildBank = 'Guild Bank'
L.LockFramePositions = 'Lock frame positions'
L.ShowEmptyItemSlotBackground = 'Display a background for empty item slots'
L.HighlightItemsByQuality = 'Highlight items by quality' 
L.HighlightQuestItems = 'Highlight quest items'
L.ReverseSlotOrdering = 'Reverse bag slot ordering'
L.ColorItemSlotsByBagType = 'Color empty item slots by bag type'
L.FrameLayer = 'Layer'
L.EnableBagFrame = 'Enable bag frame'
L.EnableMoneyFrame = 'Enable money frame'
L.EnableDBOFrame = 'Enable databroker frame'
L.EnableSearchToggle = 'Enable search toggle'
L.EnableOptionsToggle = 'Enable options toggle'
L.EnableFrame_inventory = 'Enable inventory frame'
L.EnableFrame_bank = 'Enable bank frame'
L.EnableFrame_keys = 'Enable keyring'
L.SettingRequiresRestart = 'This setting will take effect the next time you log in'
L.EnableAutoDisplay_bank = 'Display inventory when visiting the bank'
L.EnableAutoDisplay_ah = 'Display inventory when visiting the auction house'
L.EnableAutoDisplay_vendor = 'Display inventory when visiting a vendor'
L.EnableAutoDisplay_trade = 'Display inventory when trading items'
L.EnableAutoDisplay_craft = 'Display inventory when crafting'
L.EnableAutoDisplay_mail = 'Display inventory when checking a mailbox'
L.EnableAutoDisplay_guildbank = 'Display inventory when visiting the guild bank'
L.EnableAutoDisplay_player = 'Display inventory when opening the player frame'
L.DisplaySettings = 'Automatic Display'
L.DisplaySettingsTitle = 'Automatic frame display settings'
L.FrameSettings = 'Frame Settings'
L.FrameSettingsTitle = 'Configuration settings specific to a Bagnon frame'
L.GeneralSettings = 'General Settings'
L.GeneralSettingsTitle = 'General configuration settings for Bagnon'
L.EnableBlizzardBagPassThrough = 'Display Blizzard frames for disabled bags'
L.EnableBagBreak = 'Enable bag break layout'
L.ColorSettings = 'Color Settings'
L.ColorSettingsTitle = 'Item slot coloring settings'
L.ItemHighlightOpacity = 'Item highlight brightness'
L.ItemSlotColor_ammo = 'Ammo bag slot color'
L.ItemSlotColor_trade = 'Trade bag slot color'
L.ItemSlotColor_shard = 'Soul bag slot color'
L.ItemSlotColor_keyring = 'Keyring slot color'