--[[
	Bagnon Config Localization Information: Translated by StingerSoft
		This file must be present to have partial translations
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'ruRU')
if not L then return end

L.Columns = 'Колонок'
L.Scale = 'Масштаб'
L.Spacing = 'Промежуток'
L.Opacity = 'Прозрачность'
L.FrameColor = 'Цвет окна'
L.FrameBorderColor = 'Цвет граници окна'
L.Frame = 'Окно'
L.Inventory = 'Инвентарь'
L.Bank = 'Банк'
L.KeyRing = 'Связка ключей'
L.GuildBank = 'Банк гильдии'
L.LockFramePositions = 'Закрепить позицию окна'
L.ShowEmptyItemSlotBackground = 'Отображать фон пустых ячеек'
L.HighlightItemsByQuality = 'Подсветка предметов по качеству' 
L.HighlightQuestItems = 'Подсветка предметов для задания'
L.ReverseSlotOrdering = 'Обратить порядок ячеек сумкок'
L.ColorItemSlotsByBagType = 'Цвет пустых ячеек по типу сумки'
L.FrameLayer = 'Слой окна'
L.EnableBagFrame = 'Показывать кнопку сумок'
L.EnableMoneyFrame = 'Показывать область денег'
L.EnableDBOFrame = 'Показывать область databroker'
L.EnableSearchToggle = 'Показывать кнопку поиска'
L.EnableOptionsToggle = 'Показывать кнопку настроек'
L.EnableFrame_inventory = 'Включить область инвентаря'
L.EnableFrame_bank = 'Включить область банка'
L.EnableFrame_keys = 'Включить связку ключей'
L.SettingRequiresRestart = 'Настройки вступят в силу после следующего входа в игру или перезагрузки интерфейса,\nКомандой: /reloadui.'
L.EnableAutoDisplay_bank = 'Показать инвентарь при посещении банка.'
L.EnableAutoDisplay_ah = 'Показать инвентарь при посещении аукциона.'
L.EnableAutoDisplay_vendor = 'Показать инвентарь при посещении торговца.'
L.EnableAutoDisplay_trade = 'Показать инвентарь при обмене предметами.'
L.EnableAutoDisplay_craft = 'Показать инвентарь во время изготовления.'
L.EnableAutoDisplay_mail = 'Показать инвентарь во время просмотра почты.'
L.EnableAutoDisplay_guildbank = 'Показать инвентарь при посещении банка гильдии.'
L.EnableAutoDisplay_player = 'Показать инвентарь при открытии окна игрока.'
L.DisplaySettings = 'Настройки авто показа'
L.DisplaySettingsTitle = 'Настройки автоматического открытия окна.'
L.FrameSettings = 'Настройки окна'
L.FrameSettingsTitle = 'Настройка окна Bagnon.'
L.GeneralSettings = 'Основные настройки'
L.GeneralSettingsTitle = 'Основные настройки Bagnon.'
L.EnableBlizzardBagPassThrough = 'Открывать стандартные окна для отключенных сумок.'
L.EnableBagBreak = 'Включить прерывание размещения сумок'
L.ColorSettings = 'Настройка окраски'
L.ColorSettingsTitle = 'Настройки окраски ячеек предметов'
L.ItemHighlightOpacity = 'Яркость подсветки предметов'
L.ItemSlotColor_ammo = 'Окраска ячейки боеприпасов'
L.ItemSlotColor_trade = 'Окраска ячейки товаров'
L.ItemSlotColor_shard = 'Окраска ячейки камней'
L.ItemSlotColor_keyring = 'Окраска ячейки ключей'