--[[
	Bagnon Config Localization Information: German Language
--]]

local L = LibStub('AceLocale-3.0'):NewLocale('Bagnon-Config', 'deDE')
if not L then return end

L.Columns = 'Spalten'
L.Scale = 'Skalierung'
L.Spacing = 'Abstand'
L.Opacity = 'Transparenz'
L.FrameColor = 'Farbe des Fensters'
L.FrameBorderColor = 'Farbe des Fensterrands'
L.Frame = 'Fenster'
L.Inventory = 'Inventar'
L.Bank = 'Bank'
L.KeyRing = 'Schl\195\188sselbund'
L.GuildBank = 'Gildenbank'
L.LockFramePositions = 'Fensterpositionen sperren'
L.ShowEmptyItemSlotBackground = 'Zeige einen Hintergrund f\195\188r leere Gegenstandslots'
L.HighlightItemsByQuality = 'Gegenst\195\164nde nach der Seltenheit hervorheben' 
L.HighlightQuestItems = 'Questgegenst\195\164nde hervorheben'
L.ReverseSlotOrdering = 'Anordnung der Slots umdrehen'
L.ColorItemSlotsByBagType = 'Leere Gegenstandslots nach der Taschen-Art einf\195\164rben'
L.FrameLayer = 'Layer'
L.EnableBagFrame = 'Taschen-Anzeige aktivieren'
L.EnableMoneyFrame = 'Gold-Anzeige aktivieren'
L.EnableDBOFrame = 'Databroker-Anzeige aktivieren'
L.EnableSearchToggle = 'Suchfeld aktivieren'
L.EnableOptionsToggle = 'Schalter f\195\188r die Optionen aktivieren'
L.EnableFrame_inventory = 'Inventar aktivieren'
L.EnableFrame_bank = 'Bank aktivieren'
L.EnableFrame_keys = 'Schl\195\188sselbund aktivieren'
L.SettingRequiresRestart = 'Diese Einstellung wird nach dem n\195\164chsten Einloggen in Kraft treten'
L.EnableAutoDisplay_bank = 'Inventar anzeigen, wenn die Bank besucht wird'
L.EnableAutoDisplay_ah = 'Inventar anzeigen, wenn das Auktionshaus besucht wird'
L.EnableAutoDisplay_vendor = 'Inventar anzeigen, wenn ein H\195\164ndler besucht wird'
L.EnableAutoDisplay_trade = 'Inventar beim Handeln von Gegenst\195\164nden anzeigen'
L.EnableAutoDisplay_craft = 'Inventar beim Herstellen anzeigen'
L.EnableAutoDisplay_mail = 'Inventar beim Abholen der Post anzeigen'
L.EnableAutoDisplay_guildbank = 'Inventar anzeigen, wenn die Gildenbank besucht wird'
L.EnableAutoDisplay_player = 'Inventar anzeigen, wenn das Spielerfenster ge\195\182ffnet wird'
L.DisplaySettings = 'Automatische Anzeige'
L.DisplaySettingsTitle = 'Einstellungen f\195\188r das automatische \195\150ffnen der Fenster'
L.FrameSettings = 'Fenstereinstellungen'
L.FrameSettingsTitle = 'Einstellungen f\195\188r ein bestimmtes Bagnon Fenster anpassen'
L.GeneralSettings = 'Allgemeine Einstellungen'
L.GeneralSettingsTitle = 'Allgemeine Einstellungen f\195\188r Bagnon anpassen'
L.EnableBlizzardBagPassThrough = 'Blizzard Fenster f\195\188r die deaktivierten Taschen anzeigen'
L.EnableBagBreak = 'Trennen der Taschen aktivieren'
L.ColorSettings = 'Farbeinstellungen'
L.ColorSettingsTitle = 'Einstellungen f\195\188r das Einf\195\164rben der Gegenstandslots'
L.ItemHighlightOpacity = 'Helligkeit der Gegenstandshervorhebung'
L.ItemSlotColor_ammo = 'Farbe f\195\188r die Slots der Munitionstasche'
L.ItemSlotColor_trade = 'Farbe f\195\188r die Slots der Handeltasche'
L.ItemSlotColor_shard = 'Farbe f\195\188r die Slots der Seelentasche'
L.ItemSlotColor_keyring = 'Farbe f\195\188r die Slots des Schl\195\188sselbunds'